# lexicon.py

LEXICON = {
    "uk": {
        "menu_daily": "✨ Карта дня (Безкоштовно)",
        "menu_love": "❤️ Любов та Стосунки (75 ⭐️)",
        "menu_career": "💰 Гроші та Реалізація (100 ⭐️)",
        "menu_advice": "🧘 Порада Всесвіту (25 ⭐️)",
        "menu_profile": "👤 Моя карма (баланс)",
        "btn_back": "🔙 Назад в меню",
        "choose_language": "🇺🇦 Оберіть мову:\n🇬🇧 Choose your language:\n🏳️ Выберите язык:",
        "lang_saved": "✅ Мову збережено!",
        "welcome_text": "Вітаю, <b>{name}</b>. Я — Karma.\n\nЯ тут, щоб освітити твій шлях, коли стає темно. Пам'ятай: карти не вирішують за тебе, вони лише показують вірогідності.\n\nЩо турбує твою душу сьогодні?",
        "main_menu_title": "Головне меню:",
        "btn_setup_horoscope": "🔮 Налаштувати гороскоп",
        "profile_text": "<b>🧘 Твій енергетичний баланс:</b>\n✨ Доступно зірок: <b>{balance} ⭐️</b>\n\n🔮 <b>Твій знак Зодіаку:</b> {zodiac}\n\n<b>Як поповнити запаси?</b>\nУ Всесвіті діє закон обміну. Просто обери будь-який платний розклад...\n\n<i>Енергія нікуди не зникає, вона лише змінює форму.</i>",
        "loading_advice": "🌌 <i>Звертаюсь до потоку...</i>",
        "loading_tarot": "🎴 <i>Тасую карти... Звертаюсь до потоків долі...</i>",
        "not_enough_stars": "❌ <b>Недостатньо зірок!</b>\nПотрібно: {cost} ⭐️\nУ тебе: {balance} ⭐️",
        "error_generate": "Вибач, енергетичні потоки зараз нестабільні. Спробуй ще раз пізніше.",
        "more_action_btn": "💫 Відчуваєш, що це не все? Обери наступну дію 👇",
        "invoice_advice_title": "Порада Всесвіту 🧘",
        "invoice_advice_desc": "Коротка мудрість або відповідь на чітке запитання.",
        "error_payment": "Недостатньо ⭐ для оплати.",
        "ask_question": "Напишіть своє запитання Всесвіту (або відправте '...', щоб отримати загальну пораду):",
        "default_advice_request": "Загальна порада",
        "refund_note": "Твої <b>{price} ⭐️ автоматично повернуто</b>.",
        "universe_silent": "Вибач, Всесвіт зараз мовчить.",
        "universe_answer": "✨ <i>Відповідь Всесвіту:</i>",
        
        # 👇 НОВІ ТЕКСТИ ДЛЯ ТАРО 👇
        "daily_already_opened": "Твоя карта на сьогодні вже відкрита!",
        "loading_daily_1": "🔮 <i>Запитую карту дня...</i>",
        "loading_daily_2": "🧘 <i>Налаштовуюся на твої вібрації...</i>",
        "loading_daily_3": "🎴 <i>Тасую колоду...</i>",
        "daily_energy_here": "✨ <i>Енергія дня вже тут...</i>",
        "invoice_love_title": "Любов та Стосунки ❤️",
        "invoice_love_desc": "Аналіз почуттів, думок партнера та майбутнього.",
        "invoice_career_title": "Гроші та Реалізація 💰",
        "invoice_career_desc": "Аналіз фінансів, кар'єрного росту та проектів.",
        "ask_love_context": "Зосередься на людині. Напиши її ім'я та коротко опиши, що відбувається між вами зараз.",
        "ask_career_context": "Опиши свою робочу ситуацію або проект, який тебе турбує.",
        "ask_general_context": "Опиши свою ситуацію (текстом або голосом)...",
        "loading_cards": "🔮 <i>Розкладаю карти...</i>",
        "loading_love_cards": "<i>Karma розкладає карти на: Ваші почуття, Приховані думки, Майбутнє...</i>",
        "cards_on_table": "✨ <i>Карти лягли на стіл...</i>",
        "magic_interrupted": "🌪 <i>Магічний ефір раптово перервався... Карти не захотіли говорити.</i>\n\nНе хвилюйся. {refund_note} Спробуй запитати ще раз за кілька хвилин.",
        "refund_note_balance": "Твої <b>{price} ⭐️ автоматично повернуто</b> на баланс."
    },
    "en": {
        "menu_daily": "✨ Card of the Day (Free)",
        "menu_love": "❤️ Love & Relationships (75 ⭐️)",
        "menu_career": "💰 Career & Finances (100 ⭐️)",
        "menu_advice": "🧘 Universe Advice (25 ⭐️)",
        "menu_profile": "👤 My Karma (Balance)",
        "btn_back": "🔙 Back to Menu",
        "choose_language": "🇺🇦 Оберіть мову:\n🇬🇧 Choose your language:\n🏳️ Выберите язык:",
        "lang_saved": "✅ Language saved!",
        "welcome_text": "Welcome, <b>{name}</b>. I am Karma.\n\nI am here to illuminate your path when it gets dark. Remember: cards don't make decisions for you, they only show probabilities.\n\nWhat troubles your soul today?",
        "main_menu_title": "Main Menu:",
        "btn_setup_horoscope": "🔮 Setup Horoscope",
        "profile_text": "<b>🧘 Your Energy Balance:</b>\n✨ Available stars: <b>{balance} ⭐️</b>\n\n🔮 <b>Your Zodiac sign:</b> {zodiac}\n\n<b>How to replenish?</b>\nThe Universe operates on the law of exchange. Just choose any paid reading...\n\n<i>Energy never disappears, it only changes form.</i>",
        "loading_advice": "🌌 <i>Consulting the stream...</i>",
        "loading_tarot": "🎴 <i>Shuffling cards... Connecting to the flows of fate...</i>",
        "not_enough_stars": "❌ <b>Not enough stars!</b>\nNeeded: {cost} ⭐️\nYou have: {balance} ⭐️",
        "error_generate": "Sorry, energy flows are unstable right now. Try again later.",
        "more_action_btn": "💫 Feel like this isn't everything? Choose your next action 👇",
        "invoice_advice_title": "Universe Advice 🧘",
        "invoice_advice_desc": "Short wisdom or an answer to a specific question.",
        "error_payment": "Not enough ⭐ to pay.",
        "ask_question": "Write your question to the Universe (or send '...' to get a general advice):",
        "default_advice_request": "General advice",
        "refund_note": "Your <b>{price} ⭐️ have been automatically refunded</b>.",
        "universe_silent": "Sorry, the Universe is silent right now.",
        "universe_answer": "✨ <i>Universe's Answer:</i>",
        
        # 👇 НОВІ ТЕКСТИ ДЛЯ ТАРО 👇
        "daily_already_opened": "Your card for today is already open!",
        "loading_daily_1": "🔮 <i>Asking for the card of the day...</i>",
        "loading_daily_2": "🧘 <i>Tuning into your vibrations...</i>",
        "loading_daily_3": "🎴 <i>Shuffling the deck...</i>",
        "daily_energy_here": "✨ <i>The energy of the day is here...</i>",
        "invoice_love_title": "Love & Relationships ❤️",
        "invoice_love_desc": "Analysis of feelings, partner's thoughts, and future.",
        "invoice_career_title": "Career & Finances 💰",
        "invoice_career_desc": "Analysis of finances, career growth, and projects.",
        "ask_love_context": "Focus on the person. Write their name and briefly describe what is happening between you right now.",
        "ask_career_context": "Describe your work situation or project that concerns you.",
        "ask_general_context": "Describe your situation (by text or voice)...",
        "loading_cards": "🔮 <i>Laying out the cards...</i>",
        "loading_love_cards": "<i>Karma is laying out the cards for: Your feelings, Hidden thoughts, Future...</i>",
        "cards_on_table": "✨ <i>The cards are on the table...</i>",
        "magic_interrupted": "🌪 <i>The magical ether was suddenly interrupted... The cards refused to speak.</i>\n\nDon't worry. {refund_note} Try asking again in a few minutes.",
        "refund_note_balance": "Your <b>{price} ⭐️ have been automatically refunded</b> to your balance."
    },
    "ru": {
        "menu_daily": "✨ Карта дня (Бесплатно)",
        "menu_love": "❤️ Любовь и Отношения (75 ⭐️)",
        "menu_career": "💰 Деньги и Реализация (100 ⭐️)",
        "menu_advice": "🧘 Совет Вселенной (25 ⭐️)",
        "menu_profile": "👤 Моя карма (баланс)",
        "btn_back": "🔙 Назад в меню",
        "choose_language": "🇺🇦 Оберіть мову:\n🇬🇧 Choose your language:\n🏳️ Выберите язык:",
        "lang_saved": "✅ Язык сохранен!",
        "welcome_text": "Приветствую, <b>{name}</b>. Я — Karma.\n\nЯ здесь, чтобы осветить твой путь, когда становится темно. Помни: карты не решают за тебя, они лишь показывают вероятности.\n\nЧто тревожит твою душу сегодня?",
        "main_menu_title": "Главное меню:",
        "btn_setup_horoscope": "🔮 Настроить гороскоп",
        "profile_text": "<b>🧘 Твой энергетический баланс:</b>\n✨ Доступно звезд: <b>{balance} ⭐️</b>\n\n🔮 <b>Твой знак Зодиака:</b> {zodiac}\n\n<b>Как пополнить запасы?</b>\nВо Вселенной действует закон обмена. Просто выбери любой платный расклад...\n\n<i>Энергия никуда не исчезает, она лишь меняет форму.</i>",
        "loading_advice": "🌌 <i>Обращаюсь к потоку...</i>",
        "loading_tarot": "🎴 <i>Карты тасуются... Обращаюсь к потокам судьбы...</i>",
        "not_enough_stars": "❌ <b>Недостаточно звезд!</b>\nНужно: {cost} ⭐️\nУ тебя: {balance} ⭐️",
        "error_generate": "Извини, энергетические потоки сейчас нестабильны. Попробуй позже.",
        "more_action_btn": "💫 Чувствуешь, что это не всё? Выбери следующее действие 👇",
        "invoice_advice_title": "Совет Вселенной 🧘",
        "invoice_advice_desc": "Короткая мудрость или ответ на четкий вопрос.",
        "error_payment": "Недостаточно ⭐ для оплаты.",
        "ask_question": "Напишите свой вопрос Вселенной (или отправьте '...', чтобы получить общий совет):",
        "default_advice_request": "Общий совет",
        "refund_note": "Твои <b>{price} ⭐️ автоматически возвращены</b>.",
        "universe_silent": "Извини, Вселенная сейчас молчит.",
        "universe_answer": "✨ <i>Ответ Вселенной:</i>",
        
        # 👇 НОВІ ТЕКСТИ ДЛЯ ТАРО 👇
        "daily_already_opened": "Твоя карта на сегодня уже открыта!",
        "loading_daily_1": "🔮 <i>Спрашиваю карту дня...</i>",
        "loading_daily_2": "🧘 <i>Настраиваюсь на твои вибрации...</i>",
        "loading_daily_3": "🎴 <i>Тасую колоду...</i>",
        "daily_energy_here": "✨ <i>Энергия дня уже здесь...</i>",
        "invoice_love_title": "Любовь и Отношения ❤️",
        "invoice_love_desc": "Анализ чувств, мыслей партнера и будущего.",
        "invoice_career_title": "Деньги и Реализация 💰",
        "invoice_career_desc": "Анализ финансов, карьерного роста и проектов.",
        "ask_love_context": "Сосредоточься на человеке. Напиши его имя и кратко опиши, что происходит между вами сейчас.",
        "ask_career_context": "Опиши свою рабочую ситуацию или проект, который тебя беспокоит.",
        "ask_general_context": "Опиши свою ситуацию (текстом или голосом)...",
        "loading_cards": "🔮 <i>Раскладываю карты...</i>",
        "loading_love_cards": "<i>Karma раскладывает карты на: Ваши чувства, Скрытые мысли, Будущее...</i>",
        "cards_on_table": "✨ <i>Карты легли на стол...</i>",
        "magic_interrupted": "🌪 <i>Магический эфир внезапно прервался... Карты не захотели говорить.</i>\n\nНе волнуйся. {refund_note} Попробуй спросить еще раз через несколько минут.",
        "refund_note_balance": "Твои <b>{price} ⭐️ автоматически возвращены</b> на баланс."
    }
}

def get_text(lang: str, key: str) -> str:
    return LEXICON.get(lang, LEXICON["uk"]).get(key, LEXICON["uk"].get(key, key))